export const MOVIES_SEARCH_LOADING = 'MOVIES_SEARCH_LOADING';
export const MOVIES_SEARCH_SUCCESS = 'MOVIES_SEARCH_SUCCESS';

export const MOVIES_INFORMATION_SUCCESS = 'MOVIES_INFORMATION_SUCCESS';

export const MOVIES_SEARCH_ERROR = 'MOVIES_SEARCH_ERROR';
export const MOVIES_DATA_RESET = 'MOVIES_DATA_RESET';

export const CHANGE_FAVOURITE_MOVIE = 'CHANGE_FAVOURITE_MOVIE';

export const CLEAR_MOVIE_SEARCH = 'CLEAR_MOVIE_SEARCH';
export const CLEAR_SELECTED_MOVIE = 'CLEAR_SELECTED_MOVIE';
