export const MOVIES_SEARCH_LOADING = 'MOVIES_SEARCH_LOADING';
export const MOVIES_SEARCH_SUCCESS = 'MOVIES_SEARCH_SUCCESS';
export const MOVIES_SEARCH_ERROR = 'MOVIES_SEARCH_ERROR';
export const MOVES_DATA_RESET = 'MOVES_DATA_RESET';
